"""
Django settings for tact_api project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # <-- FIX: Import os to read environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# <-- FIX: CRITICAL SECURITY WARNING
# NEVER hardcode your secret key. Read it from Railway's environment variables.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
 





# Quick-start development settings - unsuitable for production

# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-_v%n0q)hehdy1e4ey+at#$s+q6yjl0s*lz53ytw^(2i_l6e_k9'



# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = False


# <-- FIX: CRITICAL SECURITY WARNING
# Set DEBUG = False in production on Railway. 


# <-- FIX: Make ALLOWED_HOSTS more secure.
# This will allow your Railway domain and local development.

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'tact-api.up.railway.app',
    'tact-3c612.web.app',
    'dankie-website.web.app',
    '.railway.app'  # Covers all railway subdomains
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'corsheaders', # <-- Good, you have this
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <-- Good, this is at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tact_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tact_api.wsgi.application'

# <-- FIX: This is the main CORS fix.
# Remove CORS_ALLOW_ALL_ORIGINS and use this instead.
# This explicitly tells your server to trust your Flutter app.
CSRF_TRUSTED_ORIGINS = [
    'https://tact-api.up.railway.app',
    'https://tact-3c612.web.app',
    'https://dankie-website.web.app',
    'http://localhost',  # Your Flutter app's origin from the error
    'http://localhost',
]

# 3. FIX: CORS SETTINGS
# To definitely fix the error, we allow all origins temporarily.
# If you want to restrict it, uncomment the list below.
CORS_ALLOW_ALL_ORIGINS = True

# You can also use this if you trust all subdomains of localhost
# CORS_ALLOWED_ORIGIN_REGEXES = [
#     r"^http://localhost:\d+$",
# ]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'